Vagrant.configure('2') do |config|
  # This setting will download the atlas box at
  # https://atlas.hashicorp.com/ferventcoder/boxes/win2012r2-x64-nocm
  config.vm.box = 'ferventcoder/win2012r2-x64-nocm'

  config.vm.provider :virtualbox do |v, override|
    # Show the GUI
    v.gui = true
    # 4GB RAM
    v.customize ["modifyvm", :id, "--memory", "4096"]
    # 2 CPUs
    v.customize ["modifyvm", :id, "--cpus", "2"]
    # Video RAM is 32 MB
    v.customize ["modifyvm", :id, "--vram", 32]
    # For better DNS resolution
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # No audo
    v.customize ["modifyvm", :id, "--audio", "none"]
    # Clipboard enabled
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
    # For performance
    v.customize ["modifyvm", :id, "--usb", "off"]
    # Huge performance gain here
    v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
  end

  config.vm.provider :vmware_fusion do |v, override|
    #override.vm.box_url = ENTER A URL TO A VALID VMWARE FUSION BASE BOX OF win2012r2
    v.gui = true
    v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    # box customizations for speed
    v.vmx["memsize"] = "2048"
    v.vmx["usb.present"] = "false"
    v.vmx["sound.present"] = "false"
    v.vmx["ide1:0.present"] = "false"
  end

  # https://www.vagrantup.com/docs/hyperv/configuration.html
  # https://technet.microsoft.com/en-us/library/dn798297(v=ws.11).aspx
  config.vm.provider :hyperv do |v, override|
    # 4GB RAM
    v.memory = 4096
    # 2 CPUs
    v.cpus = 2
    # The time in seconds to wait for the virtual machine to report an IP address
    v.ip_address_timeout = 130
    # Use differencing disk instead of cloning whole VHD
    v.differencing_disk = true
    v.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }
  end

  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.windows.halt_timeout = 20
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # open up forwarded ports from the guest system to the host.
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: 'winrm', auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 8090, id: 'web', auto_correct: true

  config.vm.provision :shell, :path => 'shell/PrepareWindows.ps1'
  config.vm.provision :shell, :path => 'shell/InstallChocolatey.ps1'

  if Vagrant::VERSION < '1.8.0'
    config.vm.provision :shell, :path => 'shell/NotifyGuiAppsOfEnvironmentChanges.ps1'
  else
    config.vm.provision :shell, :path => 'shell/NotifyGuiAppsOfEnvironmentChanges.ps1', :powershell_elevated_interactive => true
  end
end
